Tidyup and added new results
FLAMEGPU/FLAMEGPU2-concurrency-benchmark pull request #14
Opened 2021-12-23 16:32 UTC by mondus

Removed old files and updated readme, new benchmark results added

2022-01-04 11:47 UTC, ptheywood requested changes

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +	+ [Brute Force Messaging](sample/figures/v100-470.82.01/alpha.2-v100-11.0-beltsoff/speedup--small_fixed_pop_brute_force.png)
Markdown is not rendering this as a list. top level lists should not be indentend, and (probably) requires a blank line prior to the list.

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +	+ Population sizes are stepped between 128 and 1024 at intervals of 128
Markdown list not rendering correctly.

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +	+ Population sizes are stepped between 1024 and 8192 at intervals of 1024
Markdown list not rendering correctly.

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +	+ Population sizes are stepped between 1024 and 8192 at intervals of 1024
Markdown list not rendering correctly.

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +Figures can be generated from data in CSV files via a python script.
This line belongs above the Dependencies subheading.

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +The `FLAMEGPU2_INC_DIR` environment variable must be set for run-time compilation (TRC) to succeed. This can be done at the same time as execution of the model. E.g.
No longer striclty neccesary IIRC.

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +This will produce 6 `.csv` files in the `build` directory.
This one produces 9 CSVs. Might be better to put "a number of"/"multiple"

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +make
`make` is incorrect.

`cmake --build` will generate the executables, and there is no makefile in the currect directory.

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +# Configure
Either remove this comment, or add a matching `# Build` comment for the second line.

2022-01-04 11:47 UTC, ptheywood commented on README.md
> +I.e. for linux to install the dependencies into a python3 virtual environment and plot the data within `build/performance_scaling.csv`
Does not just plot `build/performance_scaling.csv`

2022-01-06 16:08 UTC, mondus commented on README.md
> +	+ [Brute Force Messaging](sample/figures/v100-470.82.01/alpha.2-v100-11.0-beltsoff/speedup--small_fixed_pop_brute_force.png)
fixed

2022-01-06 16:08 UTC, mondus commented on README.md
> +	+ Population sizes are stepped between 128 and 1024 at intervals of 128
fixed

2022-01-06 16:08 UTC, mondus commented on README.md
> +	+ Population sizes are stepped between 1024 and 8192 at intervals of 1024
fixed

2022-01-06 16:08 UTC, mondus commented on README.md
> +	+ Population sizes are stepped between 1024 and 8192 at intervals of 1024
fixed

2022-01-06 16:08 UTC, mondus commented on README.md
> +Figures can be generated from data in CSV files via a python script.
fixed

2022-01-06 16:08 UTC, mondus commented on README.md
> +The `FLAMEGPU2_INC_DIR` environment variable must be set for run-time compilation (TRC) to succeed. This can be done at the same time as execution of the model. E.g.
fixed

2022-01-06 16:08 UTC, mondus commented on README.md
> +This will produce 6 `.csv` files in the `build` directory.
fixed

2022-01-06 16:08 UTC, mondus commented on README.md
> +make
fixed

2022-01-06 16:08 UTC, mondus commented on README.md
> +I.e. for linux to install the dependencies into a python3 virtual environment and plot the data within `build/performance_scaling.csv`
fixed

2022-01-06 16:32 UTC, ptheywood approved these changes
Readme's good now, still missing falloff experiment data with concurrency enabled though (a separate issue really).

2022-01-26 16:21 UTC, merged